kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: service-pinpoint-all
  labels:
    app: service-pinpoint-all
spec:
  ports:
    - name: col-w1
      protocol: TCP
      port: 9994
      targetPort: 9994
    - name: col-w2
      protocol: UDP
      port: 9995
      targetPort: 9995
    - name: col-w3
      protocol: UDP
      port: 9996
      targetPort: 9996
    - name: web-ui
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 8412
    - name: web-port
      protocol: TCP
      port: 9997
      targetPort: 9997
    - name: hbase-webui
      protocol: TCP
      port: 16010
      targetPort: 16010
      nodePort: 8410
    - name: hba-zo
      protocol: TCP
      port: 2181
      targetPort: 2181
  selector:
    app: pod-pinpoint-all
  type: NodePort
  sessionAffinity: ClientIP
---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  namespace: default
  name: deployment-pinpoint-all
  labels:
    app: deployment-pinpoint-all
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-pinpoint-all
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-pinpoint-all
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: container-pinpoint-collector
          image: 192.168.0.177/library/elitel-pinpoint-collector:v1.0.0
          tty: true
          securityContext:
            privileged: true
          ports:
            - name: w1
              protocol: TCP
              containerPort: 9994
            - name: w2
              protocol: UDP
              containerPort: 9995
            - name: w3
              protocol: UDP
              containerPort: 9996

          env:
            - name: HBASE_HOST
              value: "127.0.0.1"
            - name: HBASE_PORT
              value: "2181"
            - name: COLLECTOR_TCP_PORT
              value: "9994"
            - name: COLLECTOR_UDP_STAT_LISTEN_PORT
              value: "9995"
            - name: COLLECTOR_UDP_SPAN_LISTEN_PORT
              value: "9996"
            - name: CLUSTER_ENABLE
              value: "true"
            - name: CLUSTER_ZOOKEEPER_ADDRESS
              value: "127.0.0.1"
            - name: FLINK_CLUSTER_ENABLE
              value: "true"
            - name: FLINK_CLUSTER_ZOOKEEPER_ADDRESS
              value: "127.0.0.1"
            - name: DISABLE_DEBUG
              value: "true"

        - name: container-pinpoint-web
          image: 192.168.0.177/library/elitel-pinpoint-web:v1.0.0
          tty: true
          securityContext:
            privileged: true
          ports:
            - name: webui
              protocol: TCP
              containerPort: 8080
            - name: webport
              protocol: TCP
              containerPort: 9997
          env:
            - name: HBASE_HOST
              value: "127.0.0.1"
            - name: HBASE_PORT
              value: "2181"
            - name: CLUSTER_ENABLE
              value: "true"
            - name: CLUSTER_ZOOKEEPER_ADDRESS
              value: "127.0.0.1"
            - name: CLUSTER_WEB_TCP_PORT
              value: "9997"
            - name: ADMIN_PASSWORD
              value: "admin123"
            - name: DISABLE_ANALYTICS
              value: "true"
            - name: ENABLE_APPLICATION_INSPECTOR
              value: "true"
            - name: DISABLE_DEBUG
              value: "true"

        - name: containers-pinpoint-hbase
          image: 192.168.0.177/library/elitel-pinpoint-hbase:v1.0.0
          tty: true
          securityContext:
            privileged: true
          ports:
            - name: webui
              protocol: TCP
              containerPort: 16010
            - name: zookeeperport
              protocol: TCP
              containerPort: 2181

      dnsPolicy: ClusterFirst
      restartPolicy: Always
