kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: service-pinpoint-collector
  labels:
    app: service-pinpoint-collector
spec:
  ports:
    - name: w1
      protocol: TCP
      port: 9994
      targetPort: 9994
    - name: w2
      protocol: UDP
      port: 9995
      targetPort: 9995
    - name: w3
      protocol: UDP
      port: 9996
      targetPort: 9996
  selector:
    app: pod-pinpoint-collector
  type: ClusterIP
  sessionAffinity: ClientIP
---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  namespace: default
  name: deployment-pinpoint-collector
  labels:
    app: deployment-pinpoint-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-pinpoint-collector
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-pinpoint-collector
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: container-pinpoint-collector
          image: 192.168.0.177/library/elitel-pinpoint-collector:v1.0.0
          tty: true
          securityContext:
            privileged: true
          ports:
            - name: w1
              protocol: TCP
              containerPort: 9994
            - name: w2
              protocol: UDP
              containerPort: 9995
            - name: w3
              protocol: UDP
              containerPort: 9996

          env:
            - name: HBASE_HOST
              value: "service-pinpoint-hbase"
            - name: HBASE_PORT
              value: "2181"
            - name: COLLECTOR_TCP_PORT
              value: "9994"
            - name: COLLECTOR_UDP_STAT_LISTEN_PORT
              value: "9995"
            - name: COLLECTOR_UDP_SPAN_LISTEN_PORT
              value: "9996"
            - name: CLUSTER_ENABLE
              value: "true"
            - name: CLUSTER_ZOOKEEPER_ADDRESS
              value: "service-pinpoint-hbase"
            - name: FLINK_CLUSTER_ENABLE
              value: "true"
            - name: FLINK_CLUSTER_ZOOKEEPER_ADDRESS
              value: "service-pinpoint-hbase"
            - name: DISABLE_DEBUG
              value: "true"
              
 
      dnsPolicy: ClusterFirst
      restartPolicy: Always

