export default [
    
        {
          title:"用户管理",
          name:"first",
          context:[
               {
                  imgsrc:require('../src/assets/sltimg/xhry.png'),
                  imgname:"巡河人员",
                  imgcode:"xhry",
                  iconShow:false,
                  iconEnable:true,
                  tableField:[
                      {
                          prop:"name",
                          label:"姓名",
                          width:"95",
                          headalign:"center",
                          align:"center"
                      },{
                          prop:"age",
                          label:"年龄",
                          width:"75",
                          headalign:"center",
                          align:"center"
                      },{
                          prop:"sex",
                          label:"性别",
                          width:"75",
                          headalign:"center",
                          align:"center"
                      },{
                          prop:"native",
                          label:"籍贯",
                          width:"77",
                          headalign:"center",
                          align:"center"
                      }
                  ]
              },{
                  imgsrc:require('../src/assets/sltimg/xhsj.png'),
                  imgname:"巡河事件",
                  imgcode:"xhsj",
                  iconShow:false,
                  iconEnable:false,
                  tableField:[
                        {
                            prop:"name",
                            label:"姓名",
                            width:"75",
                            headalign:"center",
                            align:"center"
                        }
                    ]
              },{
                  imgsrc:require('../src/assets/sltimg/gzjb.png'),
                  imgname:"公众举报",
                  imgcode:"gzjb",
                  iconShow:false,
                  iconEnable:true,
                  tableField:[
                        {
                            prop:"name",
                            label:"姓名",
                            width:"75",
                            headalign:"center",
                            align:"center"
                        }
                    ]
              }
          ]
      },{
          title:"配置管理",
          name:"second",
          context:[
            {
                imgsrc:require('../src/assets/sltimg/xhry.png'),
                imgname:"巡河信息",
                imgcode:"xhxx",
                iconShow:false,
                iconEnable:true,
                tableField:[
                    {
                        prop:"name",
                        label:"姓名",
                        width:"65",
                        align:"center"
                    },{
                        prop:"age",
                        label:"年龄",
                        width:"65",
                        align:"center"
                    }
                ]
            }
          ]
      }
  
]