export default [
    
        {
          title:"用户管理",
          name:"first",
          context:[
               {
                  imgsrc:require('../src/assets/sltimg/xhry.png'),
                  imgname:"巡河人员",
                  iconShow:true,
                  tableField:[
                      {
                          prop:"name",
                          label:"姓名",
                          width:"75",
                          align:"center"
                      },{
                          prop:"age",
                          label:"年龄",
                          width:"75",
                          align:"center"
                      },{
                          prop:"sex",
                          label:"性别",
                          width:"75",
                          align:"center"
                      },{
                          prop:"native",
                          label:"籍贯",
                          width:"67",
                          align:"center"
                      }
                  ]
              },{
                  imgsrc:require('../src/assets/sltimg/xhsj.png'),
                  imgname:"巡河事件",
                  iconShow:true
              },{
                  imgsrc:require('../src/assets/sltimg/gzjb.png'),
                  imgname:"公众举报",
                  iconShow:false
              },{
                  imgsrc:require('../src/assets/sltimg/gzjb.png'),
                  imgname:"测试信息",
                  iconShow:false
              },{
                  imgsrc:require('../src/assets/sltimg/gzjb.png'),
                  imgname:"测试内容",
                  iconShow:false
              },{
                  imgsrc:require('../src/assets/sltimg/gzjb.png'),
                  imgname:"测试结果",
                  iconShow:false
              }
          ]
      },{
          title:"配置管理",
          name:"second",
          context:[
            {
                imgsrc:require('../src/assets/sltimg/xhry.png'),
                imgname:"巡河信息",
                iconShow:true,
                tableField:[
                    {
                        prop:"name",
                        label:"姓名",
                        width:"65",
                        align:"center"
                    },{
                        prop:"age",
                        label:"年龄",
                        width:"65",
                        align:"center"
                    }
                ]
            }
          ]
      },{
          title:"角色管理",
          name:"third",
          context:[]
      },{
          title:"信息管理",
          name:"four",
          context:[]
      },{
          title:"内容管理",
          name:"five",
          context:[]
      },{
          title:"测试内容",
          name:"six",
          context:[]
      },{
          title:"我的管理",
          name:"seven",
          context:[]
      },{
          title:"它的管理",
          name:"engin",
          context:[]
      }
  
]